apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: api
  name: k8s-golang-http-api
spec:
  replicas: 4
  selector:
    name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - image: ricardohsd/golang-http-example
          name: api
          ports:
            - containerPort: 8081
              name: http-server
          command: ["go-server"]

